### PR TITLE
Add interface for depth in both forward rendering and backward propagation

### PR DESCRIPTION
**Pull request by ingra14m**
This is the visualization for depth of lego

### CODE REVIEW

**Comment by JonathonLuiten** [comment]
Note this is identical to https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/2

Even uses the same variable names...
Also, doesn't actually do the backward pass properly? 
Probably close as duplicate?

**Comment by dongshengLiu** [comment]
Hey, How can I display the depth map ?

**Comment by ingra14m** [comment]
Hi, you can refer to [#30](https://github.com/graphdeco-inria/gaussian-splatting/pull/30) in [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting)

**Comment by dongshengLiu** [comment]
> Hi, you can refer to [#30](https://github.com/graphdeco-inria/gaussian-splatting/pull/30) in [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting)

Thanks!

**Comment by JIANG-CX** [comment]
> Hi, you can refer to [#30](https://github.com/graphdeco-inria/gaussian-splatting/pull/30) in [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting)

Hi, I am encountering a "RuntimeError: CUDA error: an illegal memory access was encountered" when adding the depth backward propagation. Specifically, I mentioned that it seems to be related to the line "dL_dalpha += (c_d - accum_depth_rec) * dL_ddepth;" in the "global void launch_bounds(BLOCK_X * BLOCK_Y) renderCUDA" function in backward.cu.

**Comment by ThePassedWind** [comment]
Hi, I'd like to use your code to get depth image when training (running train.py).
However, an error occurred:
**Traceback (most recent call last):**
  File "D:\PythonWorkplace\gaussian-splatting\train.py", line 227, in <module>     training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "D:\PythonWorkplace\gaussian-splatting\train.py", line 101, in training     loss.backward()
  File "D:\CodingSoftware\Anaconda\envs\ro_gaussian_splatting\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "D:\CodingSoftware\Anaconda\envs\ro_gaussian_splatting\lib\site-packages\torch\autograd\__init__.py", line 200, in backward     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\CodingSoftware\Anaconda\envs\ro_gaussian_splatting\lib\site-packages\torch\autograd\function.py", line 275, in apply     return user_fn(self, *args)
**TypeError: _RasterizeGaussians.backward() takes 3 positional arguments but 4 were given**
Training progress:   0%|                                                                               | 0/30000 [00:00<?, ?it/s]

I have successfully tested getting depth image when running render.py.
Could you please give some suggestions about how to fix this error?

**Comment by ingra14m** [comment]
Hi, depth backpropagation should not cause an error. I guess you might have used the wrong branch. You can refer to this [PR](https://github.com/graphdeco-inria/diff-gaussian-rasterization/pull/5). 

The depth branch contains both forward and backward propagation of depth, whereas the main branch only contains the forward propagation of depth.

**Comment by ThePassedWind** [comment]
Thanks a lot, I found I forgot to convey two parameters in backward function.
The problem is solved!

**Pull request closed without merging**
